language: r

matrix:
  include:
    - os: linux
      dist: release
    - os: linux
      dist: devel
    - os: osx
      dist: oldrel
    - os: osx
      dist: release

# Copied from broom
sudo: required
cache: packages
bioc_required: true
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"


r_binary_packages:
  - rstanarm
  - rstan
  - lme4

r_packages:
  - rlang
  - bindrcpp


r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
